import os
import json
import zlib
import time
try:
    from pyvcs.objects import ObjectStore
    from pyvcs.packfile import Packer
    from pyvcs.ignore import IgnoreMatcher
    from pyvcs.branch import BranchManager
    from pyvcs.tagger import Tagger
    from pyvcs.stash import Stash
    from pyvcs.diff import unified_diff
except ImportError:
    from objects import ObjectStore
    from packfile import Packer
    from ignore import IgnoreMatcher
    from branch import BranchManager
    from tagger import Tagger
    from stash import Stash
    from diff import unified_diff

VCS_DIR = ".vcs"

class Repository:
    """Core repository manager orchestrating object store, index, and subsystems."""

    def __init__(self, root_dir: str = "."):
        self.root_dir = os.path.abspath(root_dir)
        self.vcs_dir = os.path.join(self.root_dir, VCS_DIR)

        if not os.path.exists(self.vcs_dir):
            raise SystemExit(f"Fatal: Not a pyvcs repository (or any of the parent directories). Run 'vcs init' first.")

        self.store = ObjectStore(self.root_dir)
        self.packer = Packer(self.store)
        self.ignore = IgnoreMatcher(self.root_dir)
        self.index_file = os.path.join(self.vcs_dir, "index.json")
        self.head_file = os.path.join(self.vcs_dir, "HEAD")

        self.branch_mgr = BranchManager(self)
        self.tagger = Tagger(self)
        self.stash = Stash(self)

    @staticmethod
    def init(target_dir: str = "."):
        root = os.path.abspath(target_dir)
        system_root = os.environ.get("SystemRoot", "C:\\Windows")
        if root.lower().startswith(system_root.lower()):
            raise SystemExit(f"Refusing to initialize repository inside system directory '{root}'.\nPlease 'cd' into your project directory (e.g., 'cd C:\\Users\\lokes\\vcs') before running 'vcs init'.")

        vcs_path = os.path.join(root, VCS_DIR)
        for sub in ["objects", "objects/pack", "refs/heads"]:
            os.makedirs(os.path.join(vcs_path, sub), exist_ok=True)

        head_path = os.path.join(vcs_path, "HEAD")
        if not os.path.exists(head_path):
            with open(head_path, "w", encoding="utf-8") as f:
                f.write("ref: refs/heads/main")

        main_ref = os.path.join(vcs_path, "refs", "heads", "main")
        if not os.path.exists(main_ref):
            with open(main_ref, "w", encoding="utf-8") as f:
                f.write("")

        # Auto-create a sensible default .vcsignore if the project doesn't have
        # one yet — covers the common full-stack (React + Python/FastAPI +
        # Docker) noise so a plain `vcs stage .` doesn't sweep up node_modules,
        # virtualenvs, build output, or secret files.
        vcsignore_path = os.path.join(root, ".vcsignore")
        if not os.path.exists(vcsignore_path):
            default_ignore = """# Auto-generated by 'vcs init'. Edit freely.

# Node / React
node_modules
build
dist
.next
*.log
npm-debug.log*

# Python / FastAPI
__pycache__
*.pyc
*.pyo
.venv
venv
env
*.egg-info
.pytest_cache
.mypy_cache

# Docker
*.pid

# Secrets / env files - NEVER push these
.env
.env.*
*.pem
*.key

# OS / editor noise
.DS_Store
.idea
.vscode
"""
            with open(vcsignore_path, "w", encoding="utf-8") as f:
                f.write(default_ignore)
            print(f"Created default .vcsignore (node_modules, venv, __pycache__, .env, etc.)")

        print(f"Initialized empty pyvcs repository in {vcs_path}")

    # Staging area / Index management

    def _load_index(self) -> dict:
        if os.path.exists(self.index_file):
            with open(self.index_file, "r", encoding="utf-8") as f:
                return json.load(f)
        return {}

    def _save_index(self, index: dict):
        with open(self.index_file, "w", encoding="utf-8") as f:
            json.dump(index, f, indent=2)

    def stage(self, target_path: str = "."):
        """Add file or directory contents to index staging area."""
        index = self._load_index()
        files = self._gather_files(target_path)
        staged_count = 0

        for rel_p in files:
            if self.ignore.is_ignored(rel_p):
                continue
            abs_p = os.path.join(self.root_dir, rel_p)
            if os.path.exists(abs_p) and os.path.isfile(abs_p):
                blob_sha = self.store.store_blob(abs_p)
                index[rel_p] = blob_sha
                staged_count += 1

        self._save_index(index)
        print(f"Staged {staged_count} file(s).")

    def stage_file(self, rel_path: str):
        index = self._load_index()
        abs_p = os.path.join(self.root_dir, rel_path)
        if os.path.exists(abs_p) and os.path.isfile(abs_p):
            blob_sha = self.store.store_blob(abs_p)
            index[rel_path] = blob_sha
            self._save_index(index)

    def unstage(self, rel_path: str):
        index = self._load_index()
        if rel_path in index:
            del index[rel_path]
            self._save_index(index)
            print(f"Unstaged '{rel_path}'")
        else:
            print(f"'{rel_path}' is not staged.")

    # Save (Commit)

    def save(self, message: str, author: str = "dev") -> str:
        index = self._load_index()
        if not index:
            raise SystemExit("Nothing to save (staging area is empty). Use 'vcs stage <file>' first.")

        tree_sha = self.store.store_tree(index)
        parent_sha = self._get_head_commit()
        commit_sha = self.store.store_commit(tree_sha, parent_sha, message, author)

        curr_branch = self._current_branch()
        self._update_branch_ref(curr_branch, commit_sha)
        print(f"[{curr_branch} {commit_sha[:8]}] {message}")
        return commit_sha

    # Status & Log

    def get_status_lists(self):
        staged = self._load_index()
        head_commit = self._get_head_commit()
        head_files = self._get_tree_entries(head_commit) if head_commit else {}

        all_disk_files = set(self._gather_files("."))
        all_known = set(head_files.keys()) | set(staged.keys()) | all_disk_files

        modified, deleted, added, untracked = [], [], [], []

        for fp in sorted(all_known):
            if self.ignore.is_ignored(fp):
                continue
            abs_p = os.path.join(self.root_dir, fp)
            on_disk = os.path.exists(abs_p) and os.path.isfile(abs_p)

            if fp in staged:
                if not on_disk:
                    deleted.append(fp)
                else:
                    cur_sha = self.store.store_blob(abs_p)
                    if cur_sha != staged[fp]:
                        modified.append(fp)
            elif fp in head_files:
                if not on_disk:
                    deleted.append(fp)
                else:
                    cur_sha = self.store.store_blob(abs_p)
                    if cur_sha != head_files[fp]:
                        modified.append(fp)
            else:
                if on_disk:
                    untracked.append(fp)

        return modified, deleted, added, untracked

    def status(self):
        branch = self._current_branch()
        head_sha = self._get_head_commit()
        staged = self._load_index()
        modified, deleted, added, untracked = self.get_status_lists()

        print(f"On branch: {branch}")
        print(f"HEAD commit: {head_sha[:8] if head_sha else '(none)'}\n")

        print("Staged changes:")
        if staged:
            for fp in sorted(staged.keys()):
                print(f"  + {fp}")
        else:
            print("  (none)")

        print("\nUnstaged modifications / deletions:")
        if modified or deleted:
            for fp in modified:
                print(f"  m {fp}")
            for fp in deleted:
                print(f"  d {fp}")
        else:
            print("  (none)")

        print("\nUntracked files:")
        if untracked:
            for fp in untracked:
                print(f"  ? {fp}")
        else:
            print("  (none)")

    def log(self):
        sha = self._get_head_commit()
        if not sha:
            print("No commits yet.")
            return

        while sha:
            try:
                _, body = self.store.read_object(sha)
                data = json.loads(body.decode("utf-8"))
                date_str = time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(data.get("timestamp", time.time())))
                print(f"commit {sha}")
                print(f"Author: {data.get('author', 'unknown')}")
                print(f"Date:   {date_str}")
                print(f"\n    {data.get('message', '')}\n")
                sha = data.get("parent")
            except Exception as e:
                print(f"Error reading commit {sha}: {e}")
                break

    def show(self, ref: str):
        sha = self.tagger.resolve(ref)
        try:
            _, body = self.store.read_object(sha)
            data = json.loads(body.decode("utf-8"))
            print(f"Commit: {sha}")
            print(f"Author: {data.get('author')}")
            print(f"Parent: {data.get('parent') or 'none'}")
            print(f"\n    {data.get('message')}\n")
            print("Tree Files:")
            tree_entries = self._get_tree_entries(sha)
            for fp, blob in tree_entries.items():
                print(f"  {fp} ({blob[:8]})")
        except Exception as e:
            print(f"Could not show object '{ref}': {e}")

    def diff(self, ref: str = None):
        """Show diff between working directory and HEAD/ref."""
        target_commit = self.tagger.resolve(ref) if ref else self._get_head_commit()
        head_files = self._get_tree_entries(target_commit) if target_commit else {}

        disk_files = self._gather_files(".")
        all_files = sorted(set(head_files.keys()) | set(disk_files))

        for fp in all_files:
            if self.ignore.is_ignored(fp):
                continue
            old_text = ""
            if fp in head_files:
                try:
                    _, body = self.store.read_object(head_files[fp])
                    old_text = body.decode("utf-8", errors="replace")
                except Exception:
                    old_text = ""

            new_text = ""
            abs_p = os.path.join(self.root_dir, fp)
            if os.path.exists(abs_p) and os.path.isfile(abs_p):
                with open(abs_p, "r", encoding="utf-8", errors="replace") as f:
                    new_text = f.read()

            if old_text != new_text:
                d = unified_diff(old_text, new_text, f"a/{fp}", f"b/{fp}")
                if d:
                    print(d)

    def blame(self, filepath: str):
        """Line-by-line commit authorship tracking."""
        rel_p = os.path.relpath(os.path.abspath(filepath), self.root_dir).replace("\\", "/")
        commits = []
        sha = self._get_head_commit()

        while sha:
            try:
                _, body = self.store.read_object(sha)
                c_data = json.loads(body.decode("utf-8"))
                commits.append((sha, c_data))
                sha = c_data.get("parent")
            except Exception:
                break

        line_authors = {}
        for c_sha, c_data in reversed(commits):
            tree_entries = self._get_tree_entries(c_sha)
            if rel_p in tree_entries:
                try:
                    _, body = self.store.read_object(tree_entries[rel_p])
                    lines = body.decode("utf-8", errors="replace").splitlines()
                    for idx in range(len(lines)):
                        line_authors[idx] = (c_data.get("author", "dev"), c_sha[:8], c_data.get("message", ""))
                except Exception:
                    pass

        abs_p = os.path.join(self.root_dir, rel_p)
        if not os.path.exists(abs_p):
            print(f"File '{rel_p}' not found.")
            return

        with open(abs_p, "r", encoding="utf-8", errors="replace") as f:
            lines = f.read().splitlines()

        for idx, line in enumerate(lines):
            author, sha_short, msg = line_authors.get(idx, ("uncommitted", "00000000", "local edit"))
            print(f"{sha_short} ({author:<10}) {line}")

    def revert(self, filepath: str):
        """Discard local changes and restore file from HEAD commit."""
        rel_p = os.path.relpath(os.path.abspath(filepath), self.root_dir).replace("\\", "/")
        head = self._get_head_commit()
        if head:
            tree_entries = self._get_tree_entries(head)
            if rel_p in tree_entries:
                blob_sha = tree_entries[rel_p]
                _, body = self.store.read_object(blob_sha)
                self._write_workspace_file(rel_p, body)
                print(f"Reverted '{rel_p}' to HEAD state.")
                return
        # If file not in HEAD, remove untracked
        abs_p = os.path.join(self.root_dir, rel_p)
        if os.path.exists(abs_p):
            os.remove(abs_p)
            print(f"Removed untracked file '{rel_p}'")

    def revert_all(self):
        head = self._get_head_commit()
        if head:
            tree_entries = self._get_tree_entries(head)
            for fp, blob_sha in tree_entries.items():
                _, body = self.store.read_object(blob_sha)
                self._write_workspace_file(fp, body)

    def undo(self):
        """Undo last commit, keeping current changes staged."""
        head = self._get_head_commit()
        if not head:
            print("Nothing to undo.")
            return
        _, body = self.store.read_object(head)
        c_data = json.loads(body.decode("utf-8"))
        parent = c_data.get("parent") or ""
        curr_b = self._current_branch()
        self._update_branch_ref(curr_b, parent)
        print(f"Undid commit {head[:8]} (changes remain staged in index).")

    def restore(self, ref: str):
        """Restore workspace and index to a specific commit SHA or tag."""
        target_commit = self.tagger.resolve(ref)
        tree_entries = self._get_tree_entries(target_commit)
        self._checkout_commit_tree(target_commit)
        self._save_index(tree_entries)
        curr_b = self._current_branch()
        self._update_branch_ref(curr_b, target_commit)
        print(f"Restored working directory and index to {target_commit[:8]}")

    def gc(self):
        """Garbage collection: package loose objects into packfile and prune unreferenced objects."""
        reachable = set()

        # Collect commit reachable graph from all refs
        refs_dir = os.path.join(self.vcs_dir, "refs", "heads")
        if os.path.exists(refs_dir):
            for ref_name in os.listdir(refs_dir):
                ref_p = os.path.join(refs_dir, ref_name)
                with open(ref_p, "r", encoding="utf-8") as rf:
                    sha = rf.read().strip()
                while sha:
                    reachable.add(sha)
                    try:
                        _, body = self.store.read_object(sha)
                        c_data = json.loads(body.decode("utf-8"))
                        tree_sha = c_data.get("tree")
                        if tree_sha:
                            reachable.add(tree_sha)
                            tree_entries = self._get_tree_entries(sha)
                            for blob_sha in tree_entries.values():
                                reachable.add(blob_sha)
                        sha = c_data.get("parent")
                    except Exception:
                        break

        # Collect all loose objects
        obj_dir = os.path.join(self.vcs_dir, "objects")
        loose_shas = []
        for sub in os.listdir(obj_dir):
            if sub == "pack":
                continue
            sub_p = os.path.join(obj_dir, sub)
            if os.path.isdir(sub_p):
                for fn in os.listdir(sub_p):
                    loose_shas.append(sub + fn)

        to_pack = [s for s in loose_shas if s in reachable]
        to_prune = [s for s in loose_shas if s not in reachable]

        if to_pack:
            pack_name = self.packer.pack_objects(to_pack)
            print(f"Packfile generated: {pack_name}")

        for p_sha in to_prune:
            self.store.remove_loose(p_sha)

        print(f"Garbage Collection complete: Pruned {len(to_prune)} unreferenced objects.")

    # Helper utility methods

    def _gather_files(self, target_path: str = ".") -> list:
        abs_target = os.path.abspath(os.path.join(self.root_dir, target_path))
        if os.path.isfile(abs_target):
            rel = os.path.relpath(abs_target, self.root_dir).replace("\\", "/")
            return [rel]

        files = []
        for root, dirs, filenames in os.walk(abs_target):
            for fn in filenames:
                full = os.path.join(root, fn)
                rel = os.path.relpath(full, self.root_dir).replace("\\", "/")
                if not rel.startswith(VCS_DIR):
                    files.append(rel)
        return files

    def _current_branch(self) -> str:
        if os.path.exists(self.head_file):
            with open(self.head_file, "r", encoding="utf-8") as f:
                content = f.read().strip()
            if content.startswith("ref: refs/heads/"):
                return content[16:]
            return content
        return "main"

    def _get_head_commit(self) -> str:
        branch = self._current_branch()
        ref_path = os.path.join(self.vcs_dir, "refs", "heads", branch)
        if os.path.exists(ref_path):
            with open(ref_path, "r", encoding="utf-8") as f:
                return f.read().strip()
        return ""

    def _update_branch_ref(self, branch_name: str, commit_sha: str):
        ref_path = os.path.join(self.vcs_dir, "refs", "heads", branch_name)
        os.makedirs(os.path.dirname(ref_path), exist_ok=True)
        with open(ref_path, "w", encoding="utf-8") as f:
            f.write(commit_sha)

    def _get_tree_entries(self, commit_sha: str) -> dict:
        if not commit_sha:
            return {}
        try:
            _, c_body = self.store.read_object(commit_sha)
            c_data = json.loads(c_body.decode("utf-8"))
            tree_sha = c_data["tree"]
            _, t_body = self.store.read_object(tree_sha)
            return json.loads(t_body.decode("utf-8"))
        except Exception:
            return {}

    def _checkout_commit_tree(self, commit_sha: str):
        tree_entries = self._get_tree_entries(commit_sha)
        for fp, blob_sha in tree_entries.items():
            _, body = self.store.read_object(blob_sha)
            self._write_workspace_file(fp, body)

    def _write_workspace_file(self, rel_path: str, content: bytes):
        abs_p = os.path.join(self.root_dir, rel_path)
        os.makedirs(os.path.dirname(abs_p) or ".", exist_ok=True)
        with open(abs_p, "wb") as f:
            f.write(content)

    def _remove_workspace_file(self, rel_path: str):
        abs_p = os.path.join(self.root_dir, rel_path)
        if os.path.exists(abs_p):
            os.remove(abs_p)
